#!/bin/bash

#Le script lance img-search avec deux modes possibles: interactif et automatique pour lancer le programme.

image=$2

if [ $# = 0 ]
then
    echo "Aucun mode trouvé"

elif [ $1 = -i ] || [ $1 = --interactive ]
then
    #paramètres en fonction du mode interactif
    ways=""
    bool=true

    while [ $bool == true ]; do
        read -p "Entrez le chemin d'accès d'une image (cliquez sur Enter pour quitter) : " way
        if [ -f "$way" ]; then
            ways="$ways $way"
        fi
        if [ -z "$way" ]; then
            bool=false
        fi
    done

    for word in $ways ; do
        echo $word
    done | ./img-search image

elif [ $1 = -a ] || [ $1 = --automatic ]
then
    #paramètres en fonction du mode automatique
    if ! [ $3 ]
    then
        database_path=./img/
    else
        database_path=$3
    fi
    ./list-file $database_path | ./img-search image
fi
