#!/bin/bash

if [ $# -lt 3 ]; then
   echo "range-name-except exception min max"
   exit 1
fi

declare -i min="$2"
declare -i max="$3"

for i in $(seq $min $max); do
   if [ ! $i = $1 ]; then
       echo img/$i.bmp
   fi
done
